# Docker-Compose Version
version: '3.8' 

services:
  # Database | MySQL
  db:
    image: mysql:8.0.27
    container_name: wp_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wp_network

  # PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wp_network

  # WordPress
  wordpress:
    image: wordpress:latest
    container_name: wp_app_container
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_HOME: ${WORDPRESS_HOME}
      WORDPRESS_SITEURL: ${WORDPRESS_SITEURL}
    volumes:
      - ./db_data:/var/www/html
      - ./wp_content:/var/www/html/wp-content
      - ./setup.sh:/usr/local/bin/setup.sh
    entrypoint: ["/bin/bash", "/usr/local/bin/setup.sh"]
    command: ["apache2-foreground"]  # Fixed typo from 'apache2-forground' to 'apache2-foreground'
    networks:
      - wp_network

# Network Section
networks:
  wp_network:
    driver: bridge
